#!/usr/bin/env python
"""Constants for DHT library functions"""

# FILE TYPES
FILETYPE_DIR = 1
FILETYPE_DIRS = 1
FILETYPE_FILE = 2
FILETYPE_FILES = 2
FILETYPE_LINK = 4
FILETYPE_LINKS = 4
FILETYPE_ALL = 255

# TEST TYPES
TEST_LAYOUT_IS_COMPLETE = 1
TEST_LAYOUT_IS_BALANCED = 2
TEST_FILE_EXISTS_ON_HASHED_BRICKS = 4
TEST_ALL = 255
